---
- name: Setup Linux Server for development
  hosts: all
  vars_files:
    - default.config.yml
  roles:
    - role: geerlingguy.dotfiles
      when: configure_dotfiles
      tags: ['dotfiles']

  tasks:
    - name: Configure Git
      ansible.builtin.import_tasks: "tasks/gitconfig.yml"
      tags: ['gitconfig']
    - name: Configure zsh
      ansible.builtin.import_tasks: "tasks/configure_zsh.yml"
