- name: Set shell to zsh
  ansible.builtin.user:
    name: "{{ linux_user }}"
    shell: /usr/bin/zsh
  become: true
- name: Install oh-my-zsh
  ansible.builtin.shell: "KEEP_ZSHRC=yes sh -c \"$(curl -fsSL https://raw.github.com/ohmyzsh/ohmyzsh/master/tools/install.sh)\""
  args:
    creates: '~/.oh-my-zsh/oh-my-zsh.sh'
