- name: Install zsh
  ansible.builtin.apt:
    name: zsh
    state: present
  become: true
- name: Set shell to zsh
  ansible.builtin.user:
    name: "{{ linux_user }}"
    shell: /usr/bin/zsh
  become: true

- name: Detect oh-my-zsh binary
  ansible.builtin.stat:
    path: '~/.oh-my-zsh/oh-my-zsh.sh'
  register: oh_my_zsh_install

- name: Install oh-my-zsh
  ansible.builtin.shell: "KEEP_ZSHRC=yes sh -c \"$(curl -fsSL https://raw.github.com/ohmyzsh/ohmyzsh/master/tools/install.sh)\""
  when: not oh_my_zsh_install.stat.exists
